// <auto-generated>
//     Generated by Versioning.Common (F#)
// </auto-generated>
//
namespace FSharp
open System
open System.Reflection
[<assembly: AssemblyVersion("1.0.1.0")>]
[<assembly: AssemblyFileVersion("1.0.1.0")>]
[<assembly: AssemblyInformationalVersion("1.0.1-local+git-23648f1")>]
do ()
//
// Generated on C:\Projects\Repos\dparvin\Versioning.Common\src\build\Versioning.Common.targets at C:\Projects\Repos\dparvin\Versioning.Common\Code\Versioning.Common\Versioning.Common.FSharp.VC
