name: Publish Versioning.Common to NuGet

on:
  push:
    tags:
      - 'v*'  # Example: v1.0.0 or v1.0.0-beta1

jobs:
  pack-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version without 'v'
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $env:GITHUB_ENV
  
      - name: Create NuGet package
        run: nuget pack src/VersioningPackage.nuspec -OutputDirectory out -Version "${{ env.VERSION }}"

      - name: Push to NuGet
        run: nuget push "out/*.nupkg" -api-key ${{ secrets.NUGET_API_KEY }} -source https://api.nuget.org/v3/index.json -skip-duplicate
