name: Publish Versioning.Common to NuGet

on:
  push:
    tags:
      - 'v*'  # Example: v1.0.0 or v1.0.0-beta1

jobs:
  pack-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version without 'v'
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF_NAME -replace '^v', ''
          "VERSION=$version" >> $env:GITHUB_ENV
        
      - name: Create out directory
        run: mkdir -p out
        
#      - name: Nuget Version
#        run: nuget.exe
        
      - name: Create NuGet package
        working-directory: ./src
        run: nuget pack VersioningPackage.nuspec -OutputDirectory ../out -Version "${{ env.VERSION }}"
        
#      - name: List all checked-out files and folders
#        shell: pwsh
#        run: |
#          Write-Host "🗂 Listing contents of workspace directory:"
#          Get-ChildItem -Recurse -Force

      - name: Push to NuGet
        shell: pwsh
        run: |
          $packages = Get-ChildItem -Path ./out/*.nupkg
          if (-not $packages) {
            Write-Error "❌ No .nupkg files found in ./out"
            exit 1
          }

          foreach ($pkg in $packages) {
            Write-Host "📦 Pushing $($pkg.Name)..."
            nuget push $pkg.FullName `
              -ApiKey "${{ secrets.NUGET_API_KEY }}" `
              -Source https://api.nuget.org/v3/index.json `
              -SkipDuplicate `
              -Verbosity detailed
          }